### ISSUE TITLE
Forge version

### ISSUE THREAD

**Issue by Twinki14** [zeresss/MoreWaterlogging#1]
Would love to see this Forge compatible

**Comment by zeresss** [comment]
I can do this, but first I want to port my mod to previous versions down to 1.17

**Comment by zeresss** [comment]
Hi again.
I've been exploring the possibility of adapting my mod for the Forge and NeoForge loader, and during this process, I realized that supporting multiple Minecraft versions for both Forge and NeoForge would require creating distinct versions for each. After careful consideration, I've concluded that managing such an expansive project on my own would be quite challenging.
As much as I'd like to offer support for Forge, I've decided to focus my efforts on maintaining and updating the mod for the Fabric loader.
That said, if you are interested in porting the mod over to Forge, you have my full encouragement and gratitude.
Thank you for your understanding. Bye!
