### ISSUE TITLE
Modded pressure plates doesn't become waterloggable

### ISSUE THREAD

**Issue by lzm11111111** [zeresss/MoreWaterlogging#10]
When some other mod add more wood variants, the modded pressure plates doesn't become waterloggable, doors work fine.

**Comment by zeresss** [comment]
Hello. Can you provide more information about this issue. What mod are you using? What version of minecraft do you have?

**Comment by lzm11111111** [comment]
I cannot reproduce this issue, may i have misreported, sorry
