### ISSUE TITLE
1.18.2 Version Crashes Game

### ISSUE THREAD

**Issue by AgentCPU0** [zeresss/MoreWaterlogging#3]
I can't get the most recent version of the mod for 1.18.2 to run. I have the crash log, but I have no clue what it's telling me. Idk if it's an issue with the mod, my pack, my API, my libraries, anything
[crash-2024-01-17_18.23.30-client.txt](https://github.com/zeresss/more-water-logging/files/13970224/crash-2024-01-17_18.23.30-client.txt)

**Comment by zeresss** [comment]
Hi!
[Statement lib](https://modrinth.com/mod/statement) is a dependency for this mod, so consider installing it and I hope this error goes away.
