### ISSUE TITLE
request: configuration to disable Redstone dust and Redstone torch

### ISSUE THREAD

**Issue by peow** [zeresss/MoreWaterlogging#4]
it's uncomfortable to see Redstone Dust and a Redstone Torch underwater, it's good on other blocks, but not on these i think

![2024-01-24_13 06 37](https://github.com/zeresss/more-water-logging/assets/105888751/aa0557a1-1f2a-4ed9-9e24-32e9482f0ef0)

i think some people wouldn't like the Door to be waterlogged either, since they use it to breathe underwater in water monuments

and another request: the Supplementaries mod adds a block called "supplementaries:skull_pile", which allows you to put Skulls on top of others Skulls, it would be interesting for them to also be waterlogged

![2024-01-24_13 09 29](https://github.com/zeresss/more-water-logging/assets/105888751/02a276a6-e087-4a76-b60a-b23455219431)

---------------

if it is possible to add any of these functions, please update to Fabric 1.20.1 with support for Fabric Loader 0.14.22

**Comment by zeresss** [comment]
Hi!
Configuration can be added to my mod and I actually want to implement it in future updates. As for supplementaries, I think I wouldn't make any changes to this mod because this mod aimed for vanilla blocks. I really don't know what you mean by adding support for fabric 1.20.1 and 0.14.22 fabric loader, please give me more info what is wrong with my mod on these versions.

**Comment by peow** [comment]
There's nothing wrong with your mod in this version, I'm just asking that when you add configuration to your mod, that this version also supports fabric 1.20.1

**Comment by zeresss** [comment]
It will definitely support all the latest versions with config update, so stay tuned for updates.

**Comment by zeresss** [comment]
As version 1.2.0 redstone dust and redstone torch are no longer waterloggable.

**Comment by peow** [comment]
epic, tx
