### ISSUE TITLE
Doors copy the waterlogged state at another half when the only one half get waterlogged/unwaterlogged (1.20.4)

### ISSUE THREAD

**Issue by lzm11111111** [zeresss/MoreWaterlogging#9]
The doors will copy the waterlogged state when the only one half get waterlogged/unwaterlogged (I have tested in 1.20.1 and it works fine)

**Comment by zeresss** [comment]
Hi!
Thank you for your bug report. I will look into this bug closely and try to fix it as soon as possible.

**Comment by zeresss** [comment]
Hello again!
I just released version 1.2.1 of my mod with this bug fixed.
